[[authors]]
name = "Niko Matsakis"
github = "nikomatsakis"
blog = "https://smallcultfollowing.com/babysteps/"

[[authors]]
name = "Manish Goregaokar"
github = "manishearth"
blog = "https://manishearth.github.io"

[[authors]]
name = "Brian Anderson"
github = "brson"
blog = "https://brson.github.io"

[[authors]]
name = "Andrew Gallant"
github = "burntsushi"
blog = "http://blog.burntsushi.net"

