[[authors]]
name = "Andrew Gallant"
github = "burntsushi"
blog = "http://blog.burntsushi.net"

[[authors]]
name = "Brian Anderson"
github = "brson"
blog = "https://brson.github.io"

[[authors]]
name = "Bryan Cantrill"
github = "bcantrill"
blog = "http://dtrace.org/blogs/bmc"

[[authors]]
name = "Graydon Hoare"
github = "graydon"
blog = "http://graydon2.dreamwidth.org"

[[authors]]
name = "Manish Goregaokar"
github = "manishearth"
blog = "https://manishearth.github.io"

[[authors]]
name = "Niko Matsakis"
github = "nikomatsakis"
blog = "https://smallcultfollowing.com/babysteps/"
